name: Check Syntax and Run Tests

on:
  push:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9, 3.11]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
            python-version: 3.10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 unittest

      - name: Check Python version
        run: python --version

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: |
          python -m unittest discover -s tests
